// Code generated by protoc-gen-go.
// source: myproto.proto
// DO NOT EDIT!

/*
Package myproto is a generated protocol buffer package.

It is generated from these files:
	myproto.proto

It has these top-level messages:
	CreateRoomTos
	CreateRoomToc
	JoinRoomTos
	JoinRoomToc
	LeaveRoomTos
	LeaveRoomToc
	LiveTos
	LiveToc
	GetRoomsTos
	Room
	GetRoomToc
*/
package myproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoomTos struct {
	RoomName         *string `protobuf:"bytes,1,req,name=roomName" json:"roomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoomTos) Reset()                    { *m = CreateRoomTos{} }
func (m *CreateRoomTos) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomTos) ProtoMessage()               {}
func (*CreateRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRoomTos) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

type CreateRoomToc struct {
	RoomID           *int64 `protobuf:"varint,1,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoomToc) Reset()                    { *m = CreateRoomToc{} }
func (m *CreateRoomToc) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomToc) ProtoMessage()               {}
func (*CreateRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRoomToc) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type JoinRoomTos struct {
	ErrCode          *int64 `protobuf:"varint,1,req,name=errCode" json:"errCode,omitempty"`
	RoomID           *int64 `protobuf:"varint,2,req,name=roomID" json:"roomID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *JoinRoomTos) Reset()                    { *m = JoinRoomTos{} }
func (m *JoinRoomTos) String() string            { return proto.CompactTextString(m) }
func (*JoinRoomTos) ProtoMessage()               {}
func (*JoinRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinRoomTos) GetErrCode() int64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *JoinRoomTos) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

type JoinRoomToc struct {
	ErrCode          *int64 `protobuf:"varint,1,req,name=errCode" json:"errCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *JoinRoomToc) Reset()                    { *m = JoinRoomToc{} }
func (m *JoinRoomToc) String() string            { return proto.CompactTextString(m) }
func (*JoinRoomToc) ProtoMessage()               {}
func (*JoinRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JoinRoomToc) GetErrCode() int64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

type LeaveRoomTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LeaveRoomTos) Reset()                    { *m = LeaveRoomTos{} }
func (m *LeaveRoomTos) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoomTos) ProtoMessage()               {}
func (*LeaveRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type LeaveRoomToc struct {
	ErrCode          *int64 `protobuf:"varint,1,req,name=errCode" json:"errCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LeaveRoomToc) Reset()                    { *m = LeaveRoomToc{} }
func (m *LeaveRoomToc) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoomToc) ProtoMessage()               {}
func (*LeaveRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LeaveRoomToc) GetErrCode() int64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

type LiveTos struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LiveTos) Reset()                    { *m = LiveTos{} }
func (m *LiveTos) String() string            { return proto.CompactTextString(m) }
func (*LiveTos) ProtoMessage()               {}
func (*LiveTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LiveTos) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LiveToc struct {
	ErrCode          *int64 `protobuf:"varint,1,req,name=errCode" json:"errCode,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LiveToc) Reset()                    { *m = LiveToc{} }
func (m *LiveToc) String() string            { return proto.CompactTextString(m) }
func (*LiveToc) ProtoMessage()               {}
func (*LiveToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *LiveToc) GetErrCode() int64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

type GetRoomsTos struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRoomsTos) Reset()                    { *m = GetRoomsTos{} }
func (m *GetRoomsTos) String() string            { return proto.CompactTextString(m) }
func (*GetRoomsTos) ProtoMessage()               {}
func (*GetRoomsTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetRoomsTos) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Room struct {
	RoomID           *int64  `protobuf:"varint,1,req,name=roomID" json:"roomID,omitempty"`
	RoomName         *string `protobuf:"bytes,2,req,name=roomName" json:"roomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Room) GetRoomID() int64 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

func (m *Room) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

type GetRoomToc struct {
	Room             []*Room `protobuf:"bytes,1,rep,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomToc) Reset()                    { *m = GetRoomToc{} }
func (m *GetRoomToc) String() string            { return proto.CompactTextString(m) }
func (*GetRoomToc) ProtoMessage()               {}
func (*GetRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetRoomToc) GetRoom() []*Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomTos)(nil), "myproto.CreateRoomTos")
	proto.RegisterType((*CreateRoomToc)(nil), "myproto.CreateRoomToc")
	proto.RegisterType((*JoinRoomTos)(nil), "myproto.JoinRoomTos")
	proto.RegisterType((*JoinRoomToc)(nil), "myproto.JoinRoomToc")
	proto.RegisterType((*LeaveRoomTos)(nil), "myproto.LeaveRoomTos")
	proto.RegisterType((*LeaveRoomToc)(nil), "myproto.LeaveRoomToc")
	proto.RegisterType((*LiveTos)(nil), "myproto.LiveTos")
	proto.RegisterType((*LiveToc)(nil), "myproto.LiveToc")
	proto.RegisterType((*GetRoomsTos)(nil), "myproto.GetRoomsTos")
	proto.RegisterType((*Room)(nil), "myproto.room")
	proto.RegisterType((*GetRoomToc)(nil), "myproto.GetRoomToc")
}

func init() { proto.RegisterFile("myproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xad, 0x2c, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0xec, 0x50, 0xae, 0x92, 0x22, 0x17, 0xaf, 0x73, 0x51,
	0x6a, 0x62, 0x49, 0x6a, 0x50, 0x7e, 0x7e, 0x6e, 0x48, 0x7e, 0xb1, 0x90, 0x00, 0x17, 0x47, 0x11,
	0x90, 0xe9, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0xa9, 0x24, 0x8f, 0xaa, 0x24,
	0x59, 0x88, 0x8f, 0x8b, 0x0d, 0xa4, 0xc4, 0xd3, 0x05, 0xac, 0x80, 0x59, 0x49, 0x8f, 0x8b, 0xdb,
	0x2b, 0x3f, 0x33, 0x0f, 0x66, 0x02, 0x3f, 0x17, 0x7b, 0x6a, 0x51, 0x91, 0x73, 0x7e, 0x0a, 0xc4,
	0x00, 0x66, 0x24, 0xf5, 0x4c, 0x60, 0xf5, 0x72, 0xc8, 0xea, 0x93, 0x31, 0xd4, 0x2b, 0xf1, 0x71,
	0xf1, 0xf8, 0xa4, 0x26, 0x96, 0xc1, 0x9c, 0x04, 0x74, 0x00, 0x32, 0x1f, 0x8b, 0x06, 0x71, 0x2e,
	0x76, 0x9f, 0xcc, 0xb2, 0x54, 0x90, 0xe5, 0x3c, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x60, 0x09,
	0x1e, 0x25, 0x29, 0x98, 0x04, 0x16, 0x4d, 0x92, 0x5c, 0xdc, 0xee, 0xa9, 0x25, 0x20, 0x33, 0x8b,
	0x41, 0x1a, 0xb9, 0xb8, 0x98, 0x32, 0x53, 0xa0, 0x52, 0x1a, 0x5c, 0x2c, 0x20, 0x07, 0xa3, 0x7b,
	0x14, 0x25, 0x6c, 0x98, 0xc0, 0x61, 0xa3, 0xc9, 0xc5, 0x05, 0x35, 0x04, 0x64, 0x87, 0x34, 0x44,
	0x1f, 0x50, 0x35, 0xb3, 0x06, 0xb7, 0x11, 0xaf, 0x1e, 0x2c, 0xcc, 0x41, 0x82, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x5f, 0x59, 0x2a, 0x82, 0x01, 0x00, 0x00,
}
