// Code generated by protoc-gen-go.
// source: myproto.proto
// DO NOT EDIT!

/*
Package myproto is a generated protocol buffer package.

It is generated from these files:
	myproto.proto

It has these top-level messages:
	CreateRoomTos
	CreateRoomToc
	JoinRoomTos
	JoinRoomToc
	LeaveRoomTos
	LeaveRoomToc
	LiveTos
	LiveToc
	GetRoomsTos
	Room
	GetRoomToc
*/
package myproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoomTos struct {
	RoomName string `protobuf:"bytes,1,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *CreateRoomTos) Reset()                    { *m = CreateRoomTos{} }
func (m *CreateRoomTos) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomTos) ProtoMessage()               {}
func (*CreateRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRoomToc struct {
	RoomID int64 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *CreateRoomToc) Reset()                    { *m = CreateRoomToc{} }
func (m *CreateRoomToc) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomToc) ProtoMessage()               {}
func (*CreateRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type JoinRoomTos struct {
	ErrCode int64 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	RoomID  int64 `protobuf:"varint,2,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *JoinRoomTos) Reset()                    { *m = JoinRoomTos{} }
func (m *JoinRoomTos) String() string            { return proto.CompactTextString(m) }
func (*JoinRoomTos) ProtoMessage()               {}
func (*JoinRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type JoinRoomToc struct {
	ErrCode int64 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *JoinRoomToc) Reset()                    { *m = JoinRoomToc{} }
func (m *JoinRoomToc) String() string            { return proto.CompactTextString(m) }
func (*JoinRoomToc) ProtoMessage()               {}
func (*JoinRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type LeaveRoomTos struct {
}

func (m *LeaveRoomTos) Reset()                    { *m = LeaveRoomTos{} }
func (m *LeaveRoomTos) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoomTos) ProtoMessage()               {}
func (*LeaveRoomTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type LeaveRoomToc struct {
	ErrCode int64 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *LeaveRoomToc) Reset()                    { *m = LeaveRoomToc{} }
func (m *LeaveRoomToc) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoomToc) ProtoMessage()               {}
func (*LeaveRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type LiveTos struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *LiveTos) Reset()                    { *m = LiveTos{} }
func (m *LiveTos) String() string            { return proto.CompactTextString(m) }
func (*LiveTos) ProtoMessage()               {}
func (*LiveTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type LiveToc struct {
	ErrCode int64 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *LiveToc) Reset()                    { *m = LiveToc{} }
func (m *LiveToc) String() string            { return proto.CompactTextString(m) }
func (*LiveToc) ProtoMessage()               {}
func (*LiveToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetRoomsTos struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetRoomsTos) Reset()                    { *m = GetRoomsTos{} }
func (m *GetRoomsTos) String() string            { return proto.CompactTextString(m) }
func (*GetRoomsTos) ProtoMessage()               {}
func (*GetRoomsTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Room struct {
	RoomID   int64  `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	RoomName string `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetRoomToc struct {
	Room []*Room `protobuf:"bytes,1,rep,name=room" json:"room,omitempty"`
}

func (m *GetRoomToc) Reset()                    { *m = GetRoomToc{} }
func (m *GetRoomToc) String() string            { return proto.CompactTextString(m) }
func (*GetRoomToc) ProtoMessage()               {}
func (*GetRoomToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetRoomToc) GetRoom() []*Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomTos)(nil), "myproto.CreateRoomTos")
	proto.RegisterType((*CreateRoomToc)(nil), "myproto.CreateRoomToc")
	proto.RegisterType((*JoinRoomTos)(nil), "myproto.JoinRoomTos")
	proto.RegisterType((*JoinRoomToc)(nil), "myproto.JoinRoomToc")
	proto.RegisterType((*LeaveRoomTos)(nil), "myproto.LeaveRoomTos")
	proto.RegisterType((*LeaveRoomToc)(nil), "myproto.LeaveRoomToc")
	proto.RegisterType((*LiveTos)(nil), "myproto.LiveTos")
	proto.RegisterType((*LiveToc)(nil), "myproto.LiveToc")
	proto.RegisterType((*GetRoomsTos)(nil), "myproto.GetRoomsTos")
	proto.RegisterType((*Room)(nil), "myproto.room")
	proto.RegisterType((*GetRoomToc)(nil), "myproto.GetRoomToc")
}

func init() { proto.RegisterFile("myproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xad, 0x2c, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0xec, 0x50, 0xae, 0x92, 0x36, 0x17, 0xaf, 0x73, 0x51,
	0x6a, 0x62, 0x49, 0x6a, 0x50, 0x7e, 0x7e, 0x6e, 0x48, 0x7e, 0xb1, 0x90, 0x14, 0x17, 0x47, 0x11,
	0x90, 0xe9, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x2b, 0xa9,
	0xa3, 0x2a, 0x4e, 0x16, 0x12, 0xe3, 0x62, 0x03, 0x49, 0x7a, 0xba, 0x80, 0x95, 0x32, 0x07, 0x41,
	0x79, 0x4a, 0xf6, 0x5c, 0xdc, 0x5e, 0xf9, 0x99, 0x79, 0x30, 0x33, 0x25, 0xb8, 0xd8, 0x53, 0x8b,
	0x8a, 0x9c, 0xf3, 0x53, 0x52, 0xa1, 0xea, 0x60, 0x5c, 0x24, 0x03, 0x98, 0x50, 0x0c, 0x50, 0x47,
	0x36, 0x20, 0x19, 0xb7, 0x01, 0x4a, 0x7c, 0x5c, 0x3c, 0x3e, 0xa9, 0x89, 0x65, 0x30, 0xe7, 0x2b,
	0x69, 0xa0, 0xf0, 0xf1, 0xe9, 0x94, 0xe5, 0x62, 0xf7, 0xc9, 0x2c, 0x4b, 0x05, 0xb9, 0x4f, 0x88,
	0x8b, 0x25, 0x25, 0xb1, 0x24, 0x11, 0xac, 0x82, 0x27, 0x08, 0xcc, 0x56, 0x52, 0x86, 0x49, 0xe3,
	0x37, 0x83, 0xdb, 0x3d, 0xb5, 0x04, 0x64, 0x57, 0x31, 0xc8, 0x1c, 0x3e, 0x2e, 0xa6, 0xcc, 0x14,
	0xa8, 0x1a, 0x20, 0x4b, 0xc9, 0x8a, 0x8b, 0x05, 0xe4, 0x1f, 0x5c, 0xc1, 0x84, 0x12, 0xd6, 0x4c,
	0x68, 0x61, 0xad, 0xcf, 0xc5, 0x05, 0x35, 0x1a, 0xe4, 0x04, 0x45, 0x88, 0x49, 0x40, 0xfd, 0xcc,
	0x1a, 0xdc, 0x46, 0xbc, 0x7a, 0xb0, 0xd8, 0x04, 0x09, 0x06, 0x81, 0xa5, 0x92, 0xd8, 0xc0, 0x22,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x25, 0xa4, 0xea, 0xea, 0x01, 0x00, 0x00,
}
